FROM python:3.8-slim-buster
WORKDIR /app
ADD src requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
RUN chmod a+w /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
